"""M1-8 initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-16 19:49:40.468931

迁移由 `alembic revision --autogenerate` 产出，**需人工审阅**后再提交：
- 确认没有把 `op.drop_*` 混进"新增表"的迁移；
- 确认索引名、约束名符合 metadata 命名约定（DATA-CONTRACTS §5）；
- DDL 必须在 MySQL 8.0.26 上真实执行验证后方可声明通过。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['department.id'], name=op.f('fk_department_parent_id_department'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department'))
    )
    op.create_table('knowledge_gap',
    sa.Column('department_key', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('first_seen_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('last_seen_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('max_similarity', sa.Float(), nullable=True),
    sa.Column('score_type', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('suggested_category', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('open','processing','closed')", name=op.f('ck_knowledge_gap_status_values')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_gap')),
    sa.UniqueConstraint('department_key', 'fingerprint', name=op.f('uq_knowledge_gap_department_key_fingerprint'))
    )
    op.create_index('ix_knowledge_gap_status_last_seen', 'knowledge_gap', ['status', 'last_seen_at'], unique=False)
    op.create_table('mining_run',
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('pipeline_version', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_until', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('consumed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('candidates', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mining_run'))
    )
    op.create_index('ix_mining_run_status_created', 'mining_run', ['status', 'created_at'], unique=False)
    op.create_table('outbox_event',
    sa.Column('event_key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_retry_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_until', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_event')),
    sa.UniqueConstraint('event_key', name=op.f('uq_outbox_event_event_key'))
    )
    op.create_index('ix_outbox_event_status_next_retry', 'outbox_event', ['status', 'next_retry_at'], unique=False)
    op.create_table('question_cluster',
    sa.Column('representative', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_cluster'))
    )
    op.create_index('ix_question_cluster_version', 'question_cluster', ['version'], unique=False)
    op.create_table('role',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('name_norm', sa.String(length=64, collation='utf8mb4_bin'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name_norm', name=op.f('uq_role_name_norm'))
    )
    op.create_table('faq',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='candidate', nullable=False),
    sa.Column('cache_enabled', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('cluster_id', sa.BigInteger(), nullable=True),
    sa.Column('published_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('candidate','published','rejected','offline','stale')", name=op.f('ck_faq_status_values')),
    sa.ForeignKeyConstraint(['cluster_id'], ['question_cluster.id'], name=op.f('fk_faq_cluster_id_question_cluster'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq'))
    )
    op.create_index('ix_faq_cluster', 'faq', ['cluster_id'], unique=False)
    op.create_index('ix_faq_status_updated', 'faq', ['status', 'updated_at'], unique=False)
    op.create_table('faq_draft_job',
    sa.Column('job_key', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('cluster_id', sa.BigInteger(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('sources_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['question_cluster.id'], name=op.f('fk_faq_draft_job_cluster_id_question_cluster'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['mining_run.id'], name=op.f('fk_faq_draft_job_run_id_mining_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_key', name=op.f('pk_faq_draft_job')),
    sa.UniqueConstraint('run_id', 'cluster_id', name=op.f('uq_faq_draft_job_run_id_cluster_id'))
    )
    op.create_index('ix_faq_draft_job_run_status', 'faq_draft_job', ['run_id', 'status'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_permission_role_id_role'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('role_id', 'code', name=op.f('pk_role_permission'))
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('username_norm', sa.String(length=64, collation='utf8mb4_bin'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('dept_id', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('identity_revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['department.id'], name=op.f('fk_user_dept_id_department'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username_norm', name=op.f('uq_user_username_norm'))
    )
    op.create_index(op.f('ix_user_dept_id'), 'user', ['dept_id'], unique=False)
    op.create_table('auth_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revoked_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_auth_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_session'))
    )
    op.create_index('ix_auth_session_user_revoked', 'auth_session', ['user_id', 'revoked_at'], unique=False)
    op.create_table('chat_session',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_session'))
    )
    op.create_index('ix_chat_session_user_updated', 'chat_session', ['user_id', 'updated_at', 'id'], unique=False)
    op.create_table('config_revision',
    sa.Column('patch', sa.JSON(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('fk_config_revision_actor_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_revision'))
    )
    op.create_table('idempotency_record',
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('client_key', sa.String(length=128), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('fk_idempotency_record_actor_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('actor_id', 'operation', 'client_key', name=op.f('pk_idempotency_record'))
    )
    op.create_table('knowledge_unit',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('content_version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('indexed_version', sa.BigInteger(), nullable=True),
    sa.Column('index_status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('acl_version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("index_status IN ('pending', 'indexed', 'stale')", name=op.f('ck_knowledge_unit_index_status_values')),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_knowledge_unit_creator_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_unit')),
    sa.UniqueConstraint('code', name=op.f('uq_knowledge_unit_code'))
    )
    op.create_index('ix_knowledge_unit_status', 'knowledge_unit', ['is_deleted', 'enabled', 'index_status'], unique=False)
    op.create_table('operation_log',
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('fk_operation_log_actor_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_log'))
    )
    op.create_index('ix_operation_log_actor', 'operation_log', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_operation_log_resource', 'operation_log', ['resource_type', 'resource_id', 'created_at'], unique=False)
    op.create_index('ix_operation_log_trace', 'operation_log', ['trace_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_role_role_id_role'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_role_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_role'))
    )
    op.create_table('chat_request',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('auth_session_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('client_request_id', sa.String(length=128), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='accepted', nullable=False),
    sa.Column('result_type', sa.String(length=32), nullable=True),
    sa.Column('config_revision', sa.BigInteger(), nullable=False),
    sa.Column('execution_lease_until', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_seq', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('finished_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint("result_type IS NULL OR result_type IN ('answered','faq_hit','access_restricted','no_evidence','low_confidence','service_error')", name=op.f('ck_chat_request_result_type_values')),
    sa.CheckConstraint("status IN ('accepted','running','completed','rejected','failed','cancelled')", name=op.f('ck_chat_request_status_values')),
    sa.ForeignKeyConstraint(['auth_session_id'], ['auth_session.id'], name=op.f('fk_chat_request_auth_session_id_auth_session'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['config_revision'], ['config_revision.id'], name=op.f('fk_chat_request_config_revision_config_revision'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name=op.f('fk_chat_request_session_id_chat_session'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_request_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_request')),
    sa.UniqueConstraint('user_id', 'client_request_id', name=op.f('uq_chat_request_user_id_client_request_id'))
    )
    op.create_index('ix_chat_request_user_accepted', 'chat_request', ['user_id', 'accepted_at', 'id'], unique=False)
    op.create_table('cleanup_task',
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('deletion_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='queued', nullable=False),
    sa.Column('lease_until', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_unit.id'], name=op.f('fk_cleanup_task_unit_id_knowledge_unit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cleanup_task')),
    sa.UniqueConstraint('deletion_id', name=op.f('uq_cleanup_task_deletion_id'))
    )
    op.create_index('ix_cleanup_task_status', 'cleanup_task', ['status'], unique=False)
    op.create_table('index_task',
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('target_version', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='queued', nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_retry_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('lease_until', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("stage IS NULL OR stage IN ('parsing','embedding','indexing')", name=op.f('ck_index_task_stage_values')),
    sa.CheckConstraint("status IN ('queued','running','retry_wait','succeeded','failed','superseded')", name=op.f('ck_index_task_status_values')),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_unit.id'], name=op.f('fk_index_task_unit_id_knowledge_unit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_task')),
    sa.UniqueConstraint('unit_id', 'target_version', name=op.f('uq_index_task_unit_id_target_version'))
    )
    op.create_index('ix_index_task_status_next_retry', 'index_task', ['status', 'next_retry_at'], unique=False)
    op.create_table('knowledge_acl_department',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['department.id'], name=op.f('fk_knowledge_acl_department_subject_id_department'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_unit.id'], name=op.f('fk_knowledge_acl_department_unit_id_knowledge_unit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'unit_id', name=op.f('pk_knowledge_acl_department'))
    )
    op.create_index('ix_knowledge_acl_department_subject', 'knowledge_acl_department', ['subject_id'], unique=False)
    op.create_table('knowledge_acl_role',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['role.id'], name=op.f('fk_knowledge_acl_role_subject_id_role'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_unit.id'], name=op.f('fk_knowledge_acl_role_unit_id_knowledge_unit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'unit_id', name=op.f('pk_knowledge_acl_role'))
    )
    op.create_index('ix_knowledge_acl_role_subject', 'knowledge_acl_role', ['subject_id'], unique=False)
    op.create_table('knowledge_acl_user',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], name=op.f('fk_knowledge_acl_user_subject_id_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_unit.id'], name=op.f('fk_knowledge_acl_user_unit_id_knowledge_unit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'unit_id', name=op.f('pk_knowledge_acl_user'))
    )
    op.create_index('ix_knowledge_acl_user_subject', 'knowledge_acl_user', ['subject_id'], unique=False)
    op.create_table('knowledge_version',
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('file_key', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('chunk_config', sa.JSON(), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=128), nullable=False),
    sa.Column('index_generation', sa.String(length=128), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_unit.id'], name=op.f('fk_knowledge_version_unit_id_knowledge_unit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_version')),
    sa.UniqueConstraint('unit_id', 'version', name=op.f('uq_knowledge_version_unit_id_version'))
    )
    op.create_index('ix_knowledge_version_generation', 'knowledge_version', ['embedding_model_version', 'index_generation'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auth_session_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('consumed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('revoked_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['auth_session_id'], ['auth_session.id'], name=op.f('fk_refresh_token_auth_session_id_auth_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_token_token_hash'))
    )
    op.create_index('ix_refresh_token_session', 'refresh_token', ['auth_session_id'], unique=False)
    op.create_table('supplement_task',
    sa.Column('gap_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=True),
    sa.Column('target_version', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['knowledge_gap.id'], name=op.f('fk_supplement_task_gap_id_knowledge_gap'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_unit.id'], name=op.f('fk_supplement_task_unit_id_knowledge_unit'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplement_task')),
    sa.UniqueConstraint('gap_id', name=op.f('uq_supplement_task_gap_id'))
    )
    op.create_index('ix_supplement_task_status_created', 'supplement_task', ['status', 'created_at'], unique=False)
    op.create_table('chat_event',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint("event IN ('meta','delta','citations','denied','done','error')", name=op.f('ck_chat_event_event_values')),
    sa.CheckConstraint('seq > 0', name=op.f('ck_chat_event_seq_positive')),
    sa.ForeignKeyConstraint(['request_id'], ['chat_request.id'], name=op.f('fk_chat_event_request_id_chat_request'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'seq', name=op.f('pk_chat_event'))
    )
    op.create_table('chat_message',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant')", name=op.f('ck_chat_message_role_values')),
    sa.ForeignKeyConstraint(['request_id'], ['chat_request.id'], name=op.f('fk_chat_message_request_id_chat_request'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name=op.f('fk_chat_message_session_id_chat_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message')),
    sa.UniqueConstraint('request_id', 'role', name=op.f('uq_chat_message_request_id_role'))
    )
    op.create_index('ix_chat_message_session_id_id', 'chat_message', ['session_id', 'id'], unique=False)
    op.create_table('chunk',
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['unit_id', 'version'], ['knowledge_version.unit_id', 'knowledge_version.version'], name=op.f('fk_chunk_unit_id_knowledge_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk')),
    sa.UniqueConstraint('unit_id', 'version', 'seq', name=op.f('uq_chunk_unit_id_version_seq'))
    )
    op.create_table('faq_source',
    sa.Column('faq_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['faq_id'], ['faq.id'], name=op.f('fk_faq_source_faq_id_faq'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id', 'version'], ['knowledge_version.unit_id', 'knowledge_version.version'], name=op.f('fk_faq_source_unit_id_knowledge_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('faq_id', 'unit_id', name=op.f('pk_faq_source'))
    )
    op.create_index('ix_faq_source_unit', 'faq_source', ['unit_id'], unique=False)
    op.create_table('gap_request',
    sa.Column('gap_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['knowledge_gap.id'], name=op.f('fk_gap_request_gap_id_knowledge_gap'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['chat_request.id'], name=op.f('fk_gap_request_request_id_chat_request'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gap_id', 'request_id', name=op.f('pk_gap_request'))
    )
    op.create_index('ix_gap_request_request', 'gap_request', ['request_id'], unique=False)
    op.create_table('model_call_usage',
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('mining_run_id', sa.BigInteger(), nullable=True),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint("kind IN ('embedding','rerank','generation')", name=op.f('ck_model_call_usage_kind_values')),
    sa.CheckConstraint("status IN ('known','unknown','not_applicable')", name=op.f('ck_model_call_usage_status_values')),
    sa.ForeignKeyConstraint(['mining_run_id'], ['mining_run.id'], name=op.f('fk_model_call_usage_mining_run_id_mining_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['chat_request.id'], name=op.f('fk_model_call_usage_request_id_chat_request'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_call_usage')),
    sa.UniqueConstraint('call_id', name=op.f('uq_model_call_usage_call_id'))
    )
    op.create_index('ix_model_call_usage_kind_created', 'model_call_usage', ['kind', 'created_at'], unique=False)
    op.create_table('qa_audit',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('asked_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('recall_snapshot', sa.JSON(), nullable=False),
    sa.Column('allowed_snapshot', sa.JSON(), nullable=False),
    sa.Column('denied_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('first_token_ms', sa.Integer(), nullable=True),
    sa.Column('usage_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint("usage_status IN ('known','unknown','not_applicable')", name=op.f('ck_qa_audit_usage_status_values')),
    sa.ForeignKeyConstraint(['request_id'], ['chat_request.id'], name=op.f('fk_qa_audit_request_id_chat_request'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_qa_audit_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_qa_audit'))
    )
    op.create_index('ix_qa_audit_asked_at', 'qa_audit', ['asked_at'], unique=False)
    op.create_index('ix_qa_audit_user_asked', 'qa_audit', ['user_id', 'asked_at'], unique=False)
    op.create_table('cluster_member',
    sa.Column('cluster_id', sa.BigInteger(), nullable=False),
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['question_cluster.id'], name=op.f('fk_cluster_member_cluster_id_question_cluster'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_id'], ['qa_audit.request_id'], name=op.f('fk_cluster_member_log_id_qa_audit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', 'log_id', name=op.f('pk_cluster_member'))
    )
    op.create_table('message_source',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], name=op.f('fk_message_source_chunk_id_chunk'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.id'], name=op.f('fk_message_source_message_id_chat_message'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id', 'version'], ['knowledge_version.unit_id', 'knowledge_version.version'], name=op.f('fk_message_source_unit_id_knowledge_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'no', name=op.f('pk_message_source'))
    )
    op.create_index('ix_message_source_unit_version', 'message_source', ['unit_id', 'version'], unique=False)
    op.create_table('mining_consumption',
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_until', mysql.DATETIME(fsp=6), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['qa_audit.request_id'], name=op.f('fk_mining_consumption_log_id_qa_audit'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['mining_run.id'], name=op.f('fk_mining_consumption_run_id_mining_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id', 'pipeline_version', name=op.f('pk_mining_consumption'))
    )
    op.create_index('ix_mining_consumption_status_lease', 'mining_consumption', ['status', 'lease_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mining_consumption_status_lease', table_name='mining_consumption')
    op.drop_table('mining_consumption')
    op.drop_index('ix_message_source_unit_version', table_name='message_source')
    op.drop_table('message_source')
    op.drop_table('cluster_member')
    op.drop_index('ix_qa_audit_user_asked', table_name='qa_audit')
    op.drop_index('ix_qa_audit_asked_at', table_name='qa_audit')
    op.drop_table('qa_audit')
    op.drop_index('ix_model_call_usage_kind_created', table_name='model_call_usage')
    op.drop_table('model_call_usage')
    op.drop_index('ix_gap_request_request', table_name='gap_request')
    op.drop_table('gap_request')
    op.drop_index('ix_faq_source_unit', table_name='faq_source')
    op.drop_table('faq_source')
    op.drop_table('chunk')
    op.drop_index('ix_chat_message_session_id_id', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('chat_event')
    op.drop_index('ix_supplement_task_status_created', table_name='supplement_task')
    op.drop_table('supplement_task')
    op.drop_index('ix_refresh_token_session', table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index('ix_knowledge_version_generation', table_name='knowledge_version')
    op.drop_table('knowledge_version')
    op.drop_index('ix_knowledge_acl_user_subject', table_name='knowledge_acl_user')
    op.drop_table('knowledge_acl_user')
    op.drop_index('ix_knowledge_acl_role_subject', table_name='knowledge_acl_role')
    op.drop_table('knowledge_acl_role')
    op.drop_index('ix_knowledge_acl_department_subject', table_name='knowledge_acl_department')
    op.drop_table('knowledge_acl_department')
    op.drop_index('ix_index_task_status_next_retry', table_name='index_task')
    op.drop_table('index_task')
    op.drop_index('ix_cleanup_task_status', table_name='cleanup_task')
    op.drop_table('cleanup_task')
    op.drop_index('ix_chat_request_user_accepted', table_name='chat_request')
    op.drop_table('chat_request')
    op.drop_table('user_role')
    op.drop_index('ix_operation_log_trace', table_name='operation_log')
    op.drop_index('ix_operation_log_resource', table_name='operation_log')
    op.drop_index('ix_operation_log_actor', table_name='operation_log')
    op.drop_table('operation_log')
    op.drop_index('ix_knowledge_unit_status', table_name='knowledge_unit')
    op.drop_table('knowledge_unit')
    op.drop_table('idempotency_record')
    op.drop_table('config_revision')
    op.drop_index('ix_chat_session_user_updated', table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_index('ix_auth_session_user_revoked', table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_index(op.f('ix_user_dept_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('role_permission')
    op.drop_index('ix_faq_draft_job_run_status', table_name='faq_draft_job')
    op.drop_table('faq_draft_job')
    op.drop_index('ix_faq_status_updated', table_name='faq')
    op.drop_index('ix_faq_cluster', table_name='faq')
    op.drop_table('faq')
    op.drop_table('role')
    op.drop_index('ix_question_cluster_version', table_name='question_cluster')
    op.drop_table('question_cluster')
    op.drop_index('ix_outbox_event_status_next_retry', table_name='outbox_event')
    op.drop_table('outbox_event')
    op.drop_index('ix_mining_run_status_created', table_name='mining_run')
    op.drop_table('mining_run')
    op.drop_index('ix_knowledge_gap_status_last_seen', table_name='knowledge_gap')
    op.drop_table('knowledge_gap')
    op.drop_table('department')
    # ### end Alembic commands ###
