"""add upload_batch and upload_item

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-17 10:45:29.045016

迁移由 `alembic revision --autogenerate` 产出，**需人工审阅**后再提交：
- 确认没有把 `op.drop_*` 混进"新增表"的迁移；
- 确认索引名、约束名符合 metadata 命名约定（DATA-CONTRACTS §5）；
- DDL 必须在 MySQL 8.0.26 上真实执行验证后方可声明通过。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_batch',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('client_batch_id', sa.Uuid(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='received', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_upload_batch_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_batch')),
    sa.UniqueConstraint('user_id', 'client_batch_id', name=op.f('uq_upload_batch_user_id_client_batch_id'))
    )
    op.create_index('ix_upload_batch_user_status', 'upload_batch', ['user_id', 'status'], unique=False)
    op.create_table('upload_item',
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('client_file_id', sa.Uuid(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('relative_path', sa.String(length=255), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batch.id'], name=op.f('fk_upload_item_batch_id_upload_batch'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['index_task.id'], name=op.f('fk_upload_item_task_id_index_task'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_unit.id'], name=op.f('fk_upload_item_unit_id_knowledge_unit'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_upload_item_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_item')),
    sa.UniqueConstraint('user_id', 'client_file_id', name=op.f('uq_upload_item_user_id_client_file_id'))
    )
    op.create_index('ix_upload_item_batch', 'upload_item', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_upload_item_batch', table_name='upload_item')
    op.drop_table('upload_item')
    op.drop_index('ix_upload_batch_user_status', table_name='upload_batch')
    op.drop_table('upload_batch')
    # ### end Alembic commands ###
